### ISSUE TITLE
Links to mess with dns on purple and orange not working

### ISSUE THREAD

**Issue by s-williams** [jvns/mess-with-dns-backend#1]
Not sure if this is the right place to put this issue but its the place mentioned on the blog post so ¯\\\_(ツ)_/¯

On both http://purple.jvns.ca/ and http://orange.jvns.ca/

It says "It was made to be used with mess with dns" which links to https://mess-with-dns.wizardzines.com/

Which returns server not found.

Presumably this should link to https://messwithdns.net/ instead or a redirect at the wizardzines subdomain should be created.

Thanks!

**Comment by jvns** [comment]
Fixed, thanks so much for reporting!
