### ISSUE TITLE
sub domains under name

### ISSUE THREAD

**Issue by s-razoes** [jvns/mess-with-dns-backend#12]
If we add a name that has a . in the middle:
aws.amazon.com
Everything after the first dot will be ignored and will create the following sub domain:
aws.messwithdns.com

It would be fun if we could create a sub sub domain like that, say make it come out as:
aws.amazon.com.#####.messwithdns.com

**Comment by jvns** [comment]
Should be fixed now, thanks! You might have to force refresh to clear your browser cache because it's a frontend change.

**Comment by s-razoes** [comment]
Just tested it. Totally awesome.
