### ISSUE TITLE
mess-with-dns1.wizardzines.com and mess-with-dns2.wizardzines.com not reachable via TCP

### ISSUE THREAD

**Issue by mdavids** [jvns/mess-with-dns-backend#13]
`mess-with-dns1.wizardzines.com` and `mess-with-dns2.wizardzines.com` not reachable via TCP.

This may be an issue with large answers. At least, normally in DNS. But it depends, because I'm not sure if Messwithdns allows for large DNS-records, like 65k large TXT records).

**Comment by jvns** [comment]
This is interesting, it's not totally clear to me what kinds of interesting experiments having TCP support would enable.

**Comment by andrewtj** [comment]
As far as experimentation goes, some clients don't do TCP fallback at all, and often naive TCP clients don't take into account that messages sent over TCP can have the TC bit set too. I'm not sure that's all that interesting to toy with though. That said, large responses aren't uncommon (take a look at the TXT records for microsoft.com or cnn.com) so perhaps some people will want to play with them.

It may also be worth implementing along with an artificially low UDP size limit just to limit the usefulness of the service in an amplification attack (if there's not already some limits in place).

**Comment by jvns** [comment]
I needed TCP DNS to do an experiment so I implemented it. Let me know if it doesn't work!
