### ISSUE TITLE
Support for long (>256) TXT records for DKIM..?

### ISSUE THREAD

**Issue by gregsadetsky** [jvns/mess-with-dns-backend#14]
Hi again,

some DKIM TXT records are quite long, and specifically, longer than 256 chars which is the "usual" limit of TXT records.

Right now, messwithdns.net doesn't allow TXT records that are longer than 256 chars. But I do see longer TXT records in the wild, and according [to this](https://kb.isc.org/docs/aa-00356) they should be allowed as well.

I'm not sure whether you'd like to support this use case (it might be too fringe?). But I just wanted to flag it in case it was something that you'd consider adding.

Thanks again!

**Comment by jvns** [comment]
Oh, I was wondering what the array in the TXT record was for!

I've pushed what I think is a fix, though I haven't done an end-to-end test with DKIM to make sure it's working properly. Let me know if it's not working!

**Comment by gregsadetsky** [comment]
Hey, this is really great, thanks a lot!

There should probably be a limit to the record -- I was able to create a very long record in the web UI, but requesting it using dig returns a `status: SERVFAIL` (because the dns server is timing out? or the gigantic record is not a standard size?)

Trying out a few sizes, it seems that a record that's beyond ~1240 bytes (which can be created in the UI) will not be returned by dig (i.e. it will return SERVFAIL)

Thanks again!
