### ISSUE TITLE
Typo in weird experiment 4

### ISSUE THREAD

**Issue by dubek** [jvns/mess-with-dns-backend#19]
Weird experiment 4 says:

>The reason this works is that Google, Cloudflare, and Quad9 will never proactively look up our domain -- they only look up domain when someone makes a request for it. And because you're literally the only person in the world who's ever made a request for bad-ip.XYZXYZ.messwithdns.com, you have total control over when they learn about the domain for the first time.

But it should be `3-ips.XYZXYZ.messwithdns.com` in the last sentence (instead of `bad-ip....`).

**Comment by jvns** [comment]
fixed, thank you!
