### ISSUE TITLE
small typo in FAQ

### ISSUE THREAD

**Issue by mdavids** [jvns/mess-with-dns-backend#2]
_**What's the difference between messwithdns.net and messwithdns.com?**
The .com version is for serving the website, the .net version is where you're allowed to set DNS records. They're separate because it makes the site faster, more secure, and more reliable (I can use a "real" DNS server for messwithdns.net)._

I believe it's the other way around:

_The .net version is for serving the website, the .com version is where you're allowed to set DNS records._

**Comment by joek13** [comment]
I was about to report the same thing.

**Comment by jvns** [comment]
Fixed, thank you!
