### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kaimunchi** [jvns/mess-with-dns-backend#27]
If I want to expose my nameserver to the public, as you did, and resolve my own FQDN domain with an A record, do I need to add root servers to my servers?

**Comment by jvns** [comment]
I don't totally understand the question, but the answer might be "you need to add glue records"

**Comment by melsonmascarenhas** [comment]
Thank you, I got it now.

**Comment by melsonmascarenhas** [comment]
> If I want to expose my nameserver to the public, as you did, and resolve my own FQDN domain with an A record, do I need to add root servers to my servers?

Look into this you will understand https://serverfault.com/questions/309622/what-is-a-glue-record

**Comment by melsonmascarenhas** [comment]
> I don't totally understand the question, but the answer might be "you need to add glue records"

That DNS code mess is whole code or merely a portion of the code you put there?

**Comment by melsonmascarenhas** [comment]
> I don't totally understand the question, but the answer might be "you need to add glue records"

Is mess with dns is whole backend code or merely a portion of the code you put there?
