### ISSUE TITLE
TXT Record `textarea` inconsistent styling 

### ISSUE THREAD

**Issue by rorymalcolm** [jvns/mess-with-dns-backend#3]
Hi, great site that I had a lot of fun playing around with!

This is maybe deliberate, but just to let you know, on the A record input, the content input `textarea` has inconsistent styling and its hard to recognise that there is a `textarea` there at all.

Currently:
<img width="605" alt="Screenshot 2021-12-15 at 21 32 13" src="https://user-images.githubusercontent.com/1761473/146268154-049c54dd-7990-4b14-bd77-7a42ff5c453e.png">

Proposal?:
<img width="583" alt="Screenshot 2021-12-15 at 21 32 43" src="https://user-images.githubusercontent.com/1761473/146268214-2fd1fc7c-65ee-4f0f-807d-4f58d52f7fbc.png">

Super minor, but just in case it at all helped, thanks so much!

**Comment by jvns** [comment]
Thanks, I updated the CSS so it should look like this now

![image](https://user-images.githubusercontent.com/817739/146295828-9b628c3e-7edc-4fdd-986c-7700447f030e.png)
