### ISSUE TITLE
CSS issue with very long TXT record content

### ISSUE THREAD

**Issue by gregsadetsky** [jvns/mess-with-dns-backend#5]
Congrats on the great site!

I created a 255 chars TXT record with no spaces, and the non-wrapping content ended up "breaking" the table/css a bit:

<img width="1276" alt="Screen Shot 2021-12-15 at 6 00 21 PM" src="https://user-images.githubusercontent.com/1017304/146278137-a66402dd-6c0d-43ea-a210-eaa878cf7385.png">

By adding `overflow-wrap: anywhere` to the `span.view-content`, I was able to semi-fix it on mobile only (see below). On desktop however, it doesn't wrap -- the long unbroken text just widens the table.

<img width="560" alt="Screen Shot 2021-12-15 at 6 01 27 PM" src="https://user-images.githubusercontent.com/1017304/146278196-4ba0f10f-42a4-4be7-9c06-12f6d8170ddf.png">

Thanks!

**Comment by normanr** [comment]
You probably need `word-break: break-all` too if you want to fix it for desktop

**Comment by jvns** [comment]
Should be fixed now, thanks for reporting!
