### ISSUE TITLE
Empty non terminal goes wrong

### ISSUE THREAD

**Issue by mdavids** [jvns/mess-with-dns-backend#6]
Adding something like `hello.hello` (expecting `hello.hello.ocean7.messwithdns.com`), results in `hello` (`hello.messwithdns.com`) and doesn't resolve (SERVFAIL).

**Comment by jvns** [comment]
Should be fixed now, thanks! You might have to force refresh to clear your browser cache because it's a frontend change. Let me know if it's still broken.
