### ISSUE TITLE
Feature request: Add support for unknown RR types (RFC3597)

### ISSUE THREAD

**Issue by mdavids** [jvns/mess-with-dns-backend#7]
When asking for an unknown RR (`dig TYPE65000 blah.ocean7.messwithdns.com`) the Type:-value in the request output stays empty. But it would be great if it would show _TYPE65000_, according to RFC3597.

**Comment by jvns** [comment]
Made that change, thanks! It's a frontend change so you might need to force refresh to clear your browser cache.
