### ISSUE TITLE
NXDOMAIN returned for Empty Non-terminal

### ISSUE THREAD

**Issue by andrewtj** [jvns/mess-with-dns-backend#8]
If I do a query for the randomly assigned subdomain itself the server returns NXDOMAIN when it should return NODATA. NXDOMAIN signals that the name doesn't exist and there isn't any child nodes either. NODATA signals that there's no data for the QTYPE but there's either data for another TYPE at that node, or a child node with data.

https://datatracker.ietf.org/doc/html/rfc4592#section-2.2.2

**Comment by klaus-nicat** [comment]
Additional note: For long time sending NXDOMAIN instead of NOERROR for "Empty Non-Terminal" Ressource Records (ENTs) did not cause problems. But since https://datatracker.ietf.org/doc/html/rfc8020 it matters.

**Comment by jvns** [comment]
Should be fixed now, thanks! Let me know if it's not working.
