### ISSUE TITLE
Incomplete IDN support?

### ISSUE THREAD

**Issue by mdavids** [jvns/mess-with-dns-backend#9]
I can add something like `東華大學.ocean7.messwithdns.com`, but it isn't properly added as `xn--pssu7cxyrvv2a.canyon16.messwithdns.com` and neither as  `\230\157\177\232\143\175\229\164\167\229\173\184.canyon16.messwithdns.com`. 

Not sure if this is intended, but it may require some attention.

References: https://www.icann.org/resources/pages/rfcs-2012-02-25-en

**Comment by jvns** [comment]
Thanks, I added punycode support. So for example this should work now: [http://🐱.gallium8.messwithdns.com](http://🐱.gallium8.messwithdns.com). It's a frontend change so you might have to force refresh to get the new version. Let me know if it's not working!
